routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/downloadBus/{bus}','BusController@download');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/downloadApp/{app}','AppController@download');
Route::get('/downloadTech/{tech}','TechController@download');
Route::get('/download', function () {
    // Fetch the file info.
    $filePath = public_path('images/excel/template.xlsx');

    if(file_exists($filePath)) {
        $fileName = basename($filePath);
        $fileSize = filesize($filePath);

        // Output headers.
        header("Cache-Control: private");
        header("Content-Type: application/stream");
        header("Content-Disposition: attachment; filename=".$fileName);

        // Output file.
        readfile ($filePath);
        exit();
    }
    else {
        die('The provided file path is not valid.');
    }
    //return view('welcome');
});
    Route::get('/master', function () {
        return view('master');
    });

    Route::get('/test/{t}','TechController@test');
    Route::get('/delete/{bus}/{q}','BusController@delete');
    Route::get('/editerela/{app}','AppController@editrela');
    Route::get('/del/{app}/{q?}','AppController@del');
    Route::get('/deld/{dat}/{q?}','DatController@deld');
    Route::get('/delt/{tech}/{q?}','TechController@delt');
    Route::get('/delb/{bus}/{q?}','BusController@delb');
    Route::get('/dep/{bus}/{q?}/{b?}/{d?}','BusController@dep');
    Route::get('/dea/{app}/{q?}}','AppController@dep');
    Route::get('/ded/{dat}/{q?}','DatController@dep');
    Route::get('/det/{tech}/{q?}}','TechController@dep');
    Route::get('/deleted/{bus}/{q}','DatController@delete');
    Route::get('/deletet/{bus}/{q}','TechController@delete');
    Route::get('/indexapp','TestController@app');
    Route::post('/appImport','ExcelController@appImport');
    Route::post('/deImport','ExcelController@deImport');
    Route::get('/movedown/{app}','AppController@movedown');
    Route::get('/moveup/{app}','AppController@moveup');
    Route::post('/movea','AppController@movea');
    Route::get('/movedowntech/{tech}','TechController@movedown');
    Route::get('/moveuptech/{tech}','TechController@moveup');
    Route::post('/movet','TechController@movet');
    Route::post('/moveb','BusController@moveb');
    Route::get('/movedownbus/{bus}','BusController@movedown');
    Route::get('/moveupbus/{bus}','BusController@moveup');
    Route::get('/movedowndat/{dat}','DatController@movedown');
    Route::get('/moveupdat/{dat}','DatController@moveup');
    Route::post('/moved','DatController@moved');
    Route::get('/relation/{app}','AppController@relation');
    Route::post('/relation/addrelation','AppController@addrelation');
    Route::get('/relationbus/{app}','BusController@relation');
    Route::post('/relationbus/addrelation','BusController@addrelation');
    Route::get('/relationdat/{app}','DatController@relation');
    Route::post('/relationdat/addrelation','DatController@addrelation');
    Route::get('/relationtech/{app}','TechController@relation');
    Route::post('/relationtech/addrelation','TechController@addrelation');
    Route::resource('/bus','BusController');
    Route::resource('/de','DeController');
    Route::resource('/lv1','Bus_lv1Controller');
    Route::resource('/lv2','Bus_lv2Controller');
    Route::resource('/lv3','Bus_lv3Controller');
    Route::get('/buslvall','Bus_lv1Controller@all');
    Route::resource('/app','AppController');
    Route::resource('/dat','DatController');
    Route::resource('/tech','TechController');
    Route::resource('/brand','BrandController');
    Route::resource('/coll','CollController');
    Route::resource('/invol','InvolController');
    Route::resource('/lang','LangController');
    Route::resource('/place','PlaceController');
  
    Route::resource('/proc','ProcController');
    Route::resource('/ud','UdController');
    Route::resource('/state','StateController');
    Route::resource('/devg','DevgController');
    Route::get('/InApp','InController@indexApp');
    Route::get('/editApp','InController@editApp');
    Route::post('/updateApp','InController@updateApp');

    Route::get('/InDat','InController@indexDat');
    Route::get('/editDat','InController@editDat');
    Route::post('/updateDat','InController@updateDat');


//           other Artifacts
      Route::resource('/oapp','OappController');
    Route::resource('/obus','ObusController');
    Route::resource('/odata','OdataController');
    Route::resource('/otech','OtechController');
    Route::resource('/bulid','Technology_bulidController');
    Route::resource('/network','Technology_networkController');


Route::post('/brandImport','ExcelController@brandImport');
Route::post('/collImport','ExcelController@collImport');
Route::post('/involImport','ExcelController@involImport');
Route::post('/langImport','ExcelController@langImport');
Route::post('/placeImport','ExcelController@placeImport');
Route::post('/procImport','ExcelController@deImport');
Route::post('/udImport','ExcelController@udImport');
Route::post('/devgImport','ExcelController@devgImport');
Route::post('/stateImport','ExcelController@stateImport');

Route::get('/downloadotech/{app}','OtechController@download');
Route::get('/downloadoapp/{app}','OappController@download');
Route::get('/downloadodata/{app}','OdataController@download');
Route::get('/downloadobus/{app}','ObusController@download');

Route::get('/downloadbulid/{app}','Technology_bulidController@download');
Route::get('/downloadnet/{app}','Technology_networkController@download');




Route::resource('/user','UserController');

/*
Route::group( [ 'middleware' => ['web'] ], function ()
{
    //this route will use the middleware of the 'web' group, so session and auth will work here
    Route::roles();
    Route::resource('/user','UserController');

});
*/
//frontend
//Route::get('shwtst','PageController@shwtst');

/*
Route::get('/', function () {
    return view('welcome');
});*/
//frontend
//Route::get('shwtst','PageController@shwtst');

Route::get('/','frontendController@viewBus');
Route::get('/main/Bus','frontendController@viewBus');
Route::get('/main/App','frontendController@viewApp');
Route::get('/main/Dat','frontendController@viewDat');
Route::get('/main/Tec','frontendController@viewTec');

Route::get('/main/lv/{lv}/{id}','frontendController@lv');
Route::get('/main/BusDetail/{id}','frontendController@viewBusdetail');
Route::get('/main/AppDetail/{id}','frontendController@viewAppdetail');
Route::get('/main/DatDetail/{id}','frontendController@viewDatdetail');
Route::get('/main/TecDetail/{id}','frontendController@viewTecdetail');
Route::get('/downloadbus/{file}', 'frontendController@downloadbus');
Route::get('/downloaddat/{file}', 'frontendController@downloaddat');
Route::get('/downloadtec/{file}', 'frontendController@downloadtec');

Route::get('/menurelation', 'frontendController@menurelation');
Route::post('/viewrelation', 'frontendController@viewrelation');

Route::get('/Bustype/{type}','frontendController@viewBusType');
Route::get('/Dattype/{type}','frontendController@viewDatType');
Route::get('/Tectype/{type}','frontendController@viewTecType');
Route::get('/Apptype/{type}','frontendController@viewAppType');

Route::get('/Busother','frontendController@viewBusOther');
Route::get('/Appother','frontendController@viewAppOther');
Route::get('/Datother','frontendController@viewDatOther');
Route::get('/Datexcel','frontendController@viewDatExcel');
Route::get('/Tecother','frontendController@viewTecOther');
Route::get('/net','frontendController@viewnet');
Route::get('/bui','frontendController@viewbui');
Route::get('/testdrop', function () {
    return view('front.testdrop');
});
Route::get('/testsearch', function () {
    return view('front.testsearch');
});
Route::get('/testexport','frontendController@exportexcel');
/*
Route::get('/', function () {
    // Fetch the file info.
    $filePath = public_path('images/bus/3.txt');

    if(file_exists($filePath)) {
        $fileName = basename($filePath);
        $fileSize = filesize($filePath);

        // Output headers.
        header("Cache-Control: private");
        header("Content-Type: application/stream");
        header("Content-Disposition: attachment; filename=".$fileName);

        // Output file.
        readfile ($filePath);
        exit();
    }
    else {
        die('The provided file path is not valid.');
    }
    //return view('welcome');
});*/

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/app/index.blade.php
@extends('admin.layouts.template')
@section('page_heading')
@section('content')

<!--Modal add -->

<div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     xmlns="http://www.w3.org/1999/html">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Show</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="lname">รหัส</label>
                            <input type="text" class="form-control txt1" name="lname1" id="t51" disabled>
                            <label for="lname">ชื่อระบบ</label>
                            <input type="text" class="form-control txt1" name="lname1" id="t1" disabled>
                            <label for="addre">ปีที่เริ่มพัฒนา</label>
                            <input type="text" class="form-control txt1" name="addre1" id="t5" disabled>
                            <label for="addre">ภาษาที่ใช้</label>
                            <input type="text" class="form-control txt1" name="addre1" id="rela7" disabled>
                            <label for="addre">บริษัทที่พัฒนา</label>
                            <input type="text" class="form-control txt1" name="addre1" id="t4" disabled>
                            <label for="addre">ฐานข้อมูล</label>
                            <input type="text" class="form-control txt1" name="addre1" id="t3" disabled>
                            <label for="addre">ค่าซ่อมบำรุง</label>
                             <input type="text" class="form-control txt1" name="addre1" id="t8" size="10" disabled>

                            <label for="addre">รายละเอียด</label>
                            <textarea type="text" class="form-control txt1" name="addre1" id="t7" disabled style="height: 90px;"></textarea>
                            <label for="">ความสัมพันธ์กับระบบสารสนเทศ</label>
                            <textarea type="text" class="form-control txt1" name="email1" id="rela" disabled style="height: 90px;"></textarea>
                            <label for="">ความสัมพันธ์กับข้อมูล</label>
                            <textarea type="text" class="form-control txt1" name="email1" id="rela2" disabled style="height: 90px;"></textarea>
                            <label for="">ความสัมพันธ์กับเทคโนโลยี</label>
                            <textarea type="text" class="form-control txt1" name="email1" id="rela3" disabled style="height: 90px;"></textarea>
                            <label for="">ความสัมพันธ์กับหน่วยงานที่เกี่ยวข้อง</label>
                            <textarea type="text" class="form-control txt1" name="email1" id="rela6" disabled style="height: 90px;"></textarea>
                        </div>
                    </div>
                    </div>
                    <div class="col-sm-2"></div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>

            </div>
        </div>
    </div>
</div>
<?php
$i = 0 ;
$a2 = array();
$a3 = array();
foreach($a as $a1) {
    $a2[$i] = $a1->name;
    $a3[$i] = $a1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$b2 = array();
$b3 = array();
foreach($b as $b1) {
    $b2[$i] = $b1->name;
    $b3[$i] = $b1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$d2 = array();
$d3 = array();
foreach($d as $d1) {
    $d2[$i] = $d1->name;
    $d3[$i] = $d1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$t2 = array();
$t3 = array();
foreach($t as $t1) {
    $t2[$i] = $t1->name;
    $t3[$i] = $t1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$ud2 = array();
$ud3 = array();
foreach($ud as $ud1) {
    $ud2[$i] = $ud1->name;
    $ud3[$i] = $ud1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$de2 = array();
$de3 = array();
foreach($de as $de1) {
    $de2[$i] = $de1->name;
    $de3[$i] = $de1->application_layer_id;
    $i++;
}?>
<?php
$i = 0 ;
$deg2 = array();
$deg3 = array();
foreach($la as $deg1) {
    $deg2[$i] = $deg1->name;
    $deg3[$i] = $deg1->application_layer_id;
    $i++;
}?>
<class="container">
  			<div class="form-group"><h1 style="font-size:38px;">ระดับระบบสารสนเทศ</h1></div>
    @if(Session::has('message'))
    <div class="alert alert-success">{{ Session::get('message') }}</div>
    @endif
 <p> </p>
 <br>

<div class="bs-example" data-example-id="bordered-table">
    <div class="row">
        <div class="col-lg-12">
<div class="panel panel-default" >
    <div class="panel-heading">
       <div class="col-lg-3"> ตารางระบบสารสนเทศ</div><div class="col-lg-7"></div>{{ link_to_route('app.create','เพิ่มระบบสารสนเทศ',null,['class'=>'btn btn-success']) }}
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body" style="margin-right:20px;">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
                  <tr>
                      <th>รหัส</th>
                    <th>ชื่อ</th>
                    <th>หน่วยงานที่เกี่ยวข้อง</th>
                    <th>ปีที่เริ่มพัฒนา</th>
                      <th>ภาษที่ใช้พัฒนา</th>
                    <th>จัดการ</th>
                  </tr>
              </thead>
              <tbody>
                @foreach($apps as $app)
          <tr>
              @foreach($in as $in1)
@if($app->id < 10 )
              <td>{{ $in1->initial}}00{{ $app->id}} </td>
              @elseif($app->id < 100 )
              <td>{{ $in1->initial}}0{{ $app->id}} </td>
             @else
              <td>{{ $in1->initial}}{{ $app->id}} </td>
              @endif
              @endforeach
              <td>{{ $app->name}}  </td>
              <td class="col-lg-2">

                  @foreach($des as $de)
                      @if($app->id ==$de->id )
                          {{ $de->department_id}}
                      @endif
                  @endforeach

              </td>
            <td>{{ $app->getting_start_years}}  </td>
              <td>
                  @foreach($devl as $de)
                      @if($app->id ==$de->id )
                          {{ $de->develop_language}}
                      @endif
                  @endforeach
                  
              </td>
              <td  class="col-lg-3">
                  {!! Form::open(array('route'=>['app.destroy',$app->id],'method'=>'DELETE')) !!}

                  <button type="button" class="btn btn-default add" data-toggle="modal" data-target="#Add" data-id="{{ $app->id}}" data-id1="{{ $app->name}}"   data-id2="{{ $app->develop_language}}"
                          data-id3="{{ $app->app_database}}"   data-id4="{{ $app->develop_company}}"    data-id5="{{ $app->getting_start_years}}"  data-id6="{{ $app->app_relation}}"
                          data-id7="{{ $app->remark}}"   data-id8="{{ $app->ma_cost}}"    data-id9="{{ $app->department_id}}"
                          @foreach($in as $in1)
                          data-id51="{{ $in1->initial}}"
                          @endforeach
                  ><i class="fa fa fa-eye po4" aria-hidden="true"></i></button>
                  <a href="{{ action('AppController@edit' ,[$app->id] )}}" class="btn btn-default po5" ><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                      <i class="btn btn-default po6" aria-hidden="true">{!! Form::button('',['class'=>'fa fa-trash del','type'=>'submit']) !!}</i>
                  {!! Form::close() !!}
                </td>
          </tr>
        @endforeach
              </tbody>
        </table>
    </div>
    </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->
</div>
</div>
<script src="{{asset('/assets/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script>
    $(document).ready(function() {


        // $('#filer_input').filer();

        // alert('655');

        //$('tr').each(function(){
        $('.add').on('click',function(){
            //$('#add').click(function () {
            //alert('add new branch');
            //$('#Add').modal('show');

            $('#rela').val('');
            $('#rela1').val('');
            $('#rela2').val('');
            $('#rela3').val('');
            $('#rela4').val('');
            $('#rela5').val('');
            $('#rela6').val('');
            $('#rela7').val('');
            var id = $(this).attr('data-id');
            var a = <?php echo json_encode($a2); ?>;
            var aid = <?php echo json_encode($a3); ?>;
            var count = [];
            var count1 = [];
            var count2 = [];
            var count3 = [];
            var count4 = [];
            var count5 = [];
            var count6 = [];
            var count7 = [];

            // alert(id);
            var length = aid.length;
            for (var i = 0; i < aid.length; i++) {
                if (aid[i] == id) {
                    count.push(a[i]);
                    //alert(count[i]);
                    $('#rela').val(count);
                    // document.getElementById("rela").innerHTML = fruits.toString();
                }
            }
            var b = <?php echo json_encode($b2); ?>;
            var bid = <?php echo json_encode($b3); ?>;
            for (var i = 0; i < bid.length; i++) {
                if (bid[i] == id) {
                    count1.push(b[i]);
                    //alert(a[i]);
                    $('#rela1').val(count1);
                }
            }
            var d = <?php echo json_encode($d2); ?>;
            var did = <?php echo json_encode($d3); ?>;
            for (var i = 0; i < did.length; i++) {
                if (did[i] == id) {
                    count2.push(d[i]);
                    // alert(d[i]);
                    $('#rela2').val(count2);
                }
            }
            var t = <?php echo json_encode($t2); ?>;
            var tid = <?php echo json_encode($t3); ?>;
            for (var i = 0; i < tid.length; i++) {
                if (tid[i] == id) {
                    count3.push(t[i]);
                    //  alert(t[i]);
                    $('#rela3').val(count3);
                }
            }
            var ud = <?php echo json_encode($ud2); ?>;
            var udid = <?php echo json_encode($ud3); ?>;
            for (var i = 0; i < udid.length; i++) {
                if (udid[i] == id) {
                    count4.push(ud[i]);
                    //  alert(t[i]);
                    $('#rela4').val(count4);
                }
            }
            var de = <?php echo json_encode($de2); ?>;
            var deid = <?php echo json_encode($de3); ?>;
            for (var i = 0; i < deid.length; i++) {
                if (deid[i] == id) {
                    count6.push(de[i]);
                    //  alert(t[i]);
                    $('#rela6').val(count6);
                }
            }
            var deg = <?php echo json_encode($deg2); ?>;
            var degid = <?php echo json_encode($deg3); ?>;
            for (var i = 0; i < degid.length; i++) {
                if (degid[i] == id) {
                    count7.push(deg[i]);
                    //  alert(t[i]);
                    $('#rela7').val(count7);
                }
            }

        });
        //    });


    });

</script>
@stop

resources/views/app/rela.blade.php
@extends('admin.layouts.template')
@section('page_heading','Update')
@section('content')

<div class="container">
       <div class="row">
           <div class="form-group"><h1 style="font-size:38px;">ความสัมพันธ์</h1></div>
           <div class="panel panel-default">

                   <div class="panel-heading">ระบบสารสนเทศ</div>
                      <?php $type = '1' ; 
                             $a; 
                      ?>
                               <!-- /.panel-heading -->
                               <div class="panel-body" style="margin-right:20px;">
                                   <table width="100%" class="table">
                                       <thead>
                                       <tr>
                                           <th>ชื่อ</th>
                                           <th>ลบ</th>
                                       </tr>
                                       </thead>
                                       @foreach($a as $a1)
                                       <tr>
                                           <td>{{ $a1->name}}  </td>
                                           <td>

                                               <a href="{{ action('AppController@del' ,[$app,$a1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </td>
                                       </tr>
                                       @endforeach
                                       @foreach($b as $b1)
                                       <tr>
                                           <td>{{ $b1->name}}  </td>
                                           <td>
                                               <a href="{{ action('AppController@del' ,[$app,$b1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </td>
                                       </tr>
                                       @endforeach
                                       @foreach($d as $d1)
                                       <tr>
                                           <td>{{ $d1->name}}  </td>
                                           <td>
                                               <a href="{{ action('AppController@del' ,[$app,$d1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </td>
                                       </tr>
                                       @endforeach
                                       @foreach($t as $t1)
                                       <tr>
                                           <td>{{ $t1->name}}  </td>
                                           <td>
                                               <a href="{{ action('AppController@del' ,[$app,$t1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                       </tr>
                                       @endforeach
                                       @foreach($ud as $ud1)
                                     
                                           <tr>
                                               <td>{{ $ud1->name}}  </td>
                                               <td>
                                                   <a href="{{ action('AppController@del' ,[$app,$ud1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </tr>
                                       @endforeach
                                       @foreach($de as $de1)
                                       
                                           <tr>
                                               <td>{{ $de1->name}}  </td>
                                               <td>
                                                   <a href="{{ action('AppController@del' ,[$app,$de1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </tr>
                                       @endforeach
                                       @foreach($dev as $dev1)
                                      
                                           <tr>
                                               <td>{{ $dev1->name}}  </td>
                                               <td>
                                                   <a href="{{ action('AppController@del' ,[$app,$dev1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </tr>
                                       @endforeach
                                       @foreach($deg as $deg1)
                                       
                                           <tr>
                                               <td>{{ $deg1->name}}  </td>
                                               <td>
                                                   <a href="{{ action('AppController@del' ,[$app,$deg1->id] )}}" class="btn btn-danger delrela"><span class="glyphicon glyphicon-remove"></span></a>                                           </td>
                                           </tr>
                                       @endforeach

                                   </table>

                               </div>

                   </div>
               </div>

           </div>

    <script src="{{asset('/assets/bower_components/jquery/dist/jquery.min.js')}}"></script>
    <script>
        $(document).ready(function() {



    </script>

    @stop

resources/views/app/test.blade.php
<div id="main">
  <div class="container">
    <h1 style="font-size:38px;">Application</h1></div>

      @if(Session::has('message'))
<div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
  <div class="bs-example" data-example-id="bordered-table">
  <div class="panel panel-default" >
      <div class="panel-heading">
          Application Tables
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body" style="margin-right:20px;">
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                    <tr>
                      <th>id</th>
                      <th>name</th>
                      <th>develop_language</th>
                      <th>app_database</th>
                      <th>develop_company</th>
                      <th>getting_start_years</th>
                      <th>app_relation</th>
                      <th>remark</th>
                      <th>ma_cost</th>
                      <th>department_id</th>
                      <th>action</th>
                    </tr>
                </thead>
                <tbody>
                  @foreach($apps as $app)
            <tr>
              <td>{{ $app->id}}  </td>
              <td>{{ $app->name}}  </td>
              <td>{{ $app->develop_language}}  </td>
              <td>{{ $app->app_database}}  </td>
              <td>{{ $app->develop_company}}  </td>
              <td>{{ $app->getting_start_years}}  </td>
              <td>{{ $app->app_relation}}  </td>
              <td>{{ $app->remark}}  </td>
              <td>{{ $app->ma_cost}}  </td>
              <td>{{ $app->department_id}}  </td>
                  <td>
                    {!! Form::open(array('route'=>['app.destroy',$app->id],'method'=>'DELETE')) !!}
                    {{ link_to_route('app.edit','Edit',[$app->id],['class'=>'btn btn-primary']) }}
                    {!! Form::button('Delete',['class'=>'btn btn-danger','type'=>'submit']) !!}
                    {!! Form::close() !!}
                  </td>
            </tr>
          @endforeach
                </tbody>
          </table>

      </div>
      <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
  {{ link_to_route('app.create','Add New ',null,['class'=>'btn btn-success']) }}
</div>