routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/downloadBus/{bus}','BusController@download');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/downloadApp/{app}','AppController@download');
Route::get('/downloadTech/{tech}','TechController@download');
Route::get('/download', function () {
    // Fetch the file info.
    $filePath = public_path('images/excel/template.xlsx');

    if(file_exists($filePath)) {
        $fileName = basename($filePath);
        $fileSize = filesize($filePath);

        // Output headers.
        header("Cache-Control: private");
        header("Content-Type: application/stream");
        header("Content-Disposition: attachment; filename=".$fileName);

        // Output file.
        readfile ($filePath);
        exit();
    }
    else {
        die('The provided file path is not valid.');
    }
    //return view('welcome');
});
    Route::get('/master', function () {
        return view('master');
    });

    Route::get('/test/{t}','TechController@test');
    Route::get('/delete/{bus}/{q}','BusController@delete');
    Route::get('/editerela/{app}','AppController@editrela');
    Route::get('/del/{app}/{q?}','AppController@del');
    Route::get('/deld/{dat}/{q?}','DatController@deld');
    Route::get('/delt/{tech}/{q?}','TechController@delt');
    Route::get('/delb/{bus}/{q?}','BusController@delb');
    Route::get('/dep/{bus}/{q?}/{b?}/{d?}','BusController@dep');
    Route::get('/dea/{app}/{q?}}','AppController@dep');
    Route::get('/ded/{dat}/{q?}','DatController@dep');
    Route::get('/det/{tech}/{q?}}','TechController@dep');
    Route::get('/deleted/{bus}/{q}','DatController@delete');
    Route::get('/deletet/{bus}/{q}','TechController@delete');
    Route::get('/indexapp','TestController@app');
    Route::post('/appImport','ExcelController@appImport');
    Route::post('/deImport','ExcelController@deImport');
    Route::get('/movedown/{app}','AppController@movedown');
    Route::get('/moveup/{app}','AppController@moveup');
    Route::post('/movea','AppController@movea');
    Route::get('/movedowntech/{tech}','TechController@movedown');
    Route::get('/moveuptech/{tech}','TechController@moveup');
    Route::post('/movet','TechController@movet');
    Route::post('/moveb','BusController@moveb');
    Route::get('/movedownbus/{bus}','BusController@movedown');
    Route::get('/moveupbus/{bus}','BusController@moveup');
    Route::get('/movedowndat/{dat}','DatController@movedown');
    Route::get('/moveupdat/{dat}','DatController@moveup');
    Route::post('/moved','DatController@moved');
    Route::get('/relation/{app}','AppController@relation');
    Route::post('/relation/addrelation','AppController@addrelation');
    Route::get('/relationbus/{app}','BusController@relation');
    Route::post('/relationbus/addrelation','BusController@addrelation');
    Route::get('/relationdat/{app}','DatController@relation');
    Route::post('/relationdat/addrelation','DatController@addrelation');
    Route::get('/relationtech/{app}','TechController@relation');
    Route::post('/relationtech/addrelation','TechController@addrelation');
    Route::resource('/bus','BusController');
    Route::resource('/de','DeController');
    Route::resource('/lv1','Bus_lv1Controller');
    Route::resource('/lv2','Bus_lv2Controller');
    Route::resource('/lv3','Bus_lv3Controller');
    Route::get('/buslvall','Bus_lv1Controller@all');
    Route::resource('/app','AppController');
    Route::resource('/dat','DatController');
    Route::resource('/tech','TechController');
    Route::resource('/brand','BrandController');
    Route::resource('/coll','CollController');
    Route::resource('/invol','InvolController');
    Route::resource('/lang','LangController');
    Route::resource('/place','PlaceController');
  
    Route::resource('/proc','ProcController');
    Route::resource('/ud','UdController');
    Route::resource('/state','StateController');
    Route::resource('/devg','DevgController');
    Route::get('/InApp','InController@indexApp');
    Route::get('/editApp','InController@editApp');
    Route::post('/updateApp','InController@updateApp');

    Route::get('/InDat','InController@indexDat');
    Route::get('/editDat','InController@editDat');
    Route::post('/updateDat','InController@updateDat');


//           other Artifacts
      Route::resource('/oapp','OappController');
    Route::resource('/obus','ObusController');
    Route::resource('/odata','OdataController');
    Route::resource('/otech','OtechController');
    Route::resource('/bulid','Technology_bulidController');
    Route::resource('/network','Technology_networkController');


Route::post('/brandImport','ExcelController@brandImport');
Route::post('/collImport','ExcelController@collImport');
Route::post('/involImport','ExcelController@involImport');
Route::post('/langImport','ExcelController@langImport');
Route::post('/placeImport','ExcelController@placeImport');
Route::post('/procImport','ExcelController@deImport');
Route::post('/udImport','ExcelController@udImport');
Route::post('/devgImport','ExcelController@devgImport');
Route::post('/stateImport','ExcelController@stateImport');

Route::get('/downloadotech/{app}','OtechController@download');
Route::get('/downloadoapp/{app}','OappController@download');
Route::get('/downloadodata/{app}','OdataController@download');
Route::get('/downloadobus/{app}','ObusController@download');

Route::get('/downloadbulid/{app}','Technology_bulidController@download');
Route::get('/downloadnet/{app}','Technology_networkController@download');




Route::resource('/user','UserController');

/*
Route::group( [ 'middleware' => ['web'] ], function ()
{
    //this route will use the middleware of the 'web' group, so session and auth will work here
    Route::roles();
    Route::resource('/user','UserController');

});
*/
//frontend
//Route::get('shwtst','PageController@shwtst');

/*
Route::get('/', function () {
    return view('welcome');
});*/
//frontend
//Route::get('shwtst','PageController@shwtst');

Route::get('/','frontendController@viewBus');
Route::get('/main/Bus','frontendController@viewBus');
Route::get('/main/App','frontendController@viewApp');
Route::get('/main/Dat','frontendController@viewDat');
Route::get('/main/Tec','frontendController@viewTec');

Route::get('/main/lv/{lv}/{id}','frontendController@lv');
Route::get('/main/BusDetail/{id}','frontendController@viewBusdetail');
Route::get('/main/AppDetail/{id}','frontendController@viewAppdetail');
Route::get('/main/DatDetail/{id}','frontendController@viewDatdetail');
Route::get('/main/TecDetail/{id}','frontendController@viewTecdetail');
Route::get('/downloadbus/{file}', 'frontendController@downloadbus');
Route::get('/downloaddat/{file}', 'frontendController@downloaddat');
Route::get('/downloadtec/{file}', 'frontendController@downloadtec');

Route::get('/menurelation', 'frontendController@menurelation');
Route::post('/viewrelation', 'frontendController@viewrelation');

Route::get('/Bustype/{type}','frontendController@viewBusType');
Route::get('/Dattype/{type}','frontendController@viewDatType');
Route::get('/Tectype/{type}','frontendController@viewTecType');
Route::get('/Apptype/{type}','frontendController@viewAppType');

Route::get('/Busother','frontendController@viewBusOther');
Route::get('/Appother','frontendController@viewAppOther');
Route::get('/Datother','frontendController@viewDatOther');
Route::get('/Datexcel','frontendController@viewDatExcel');
Route::get('/Tecother','frontendController@viewTecOther');
Route::get('/net','frontendController@viewnet');
Route::get('/bui','frontendController@viewbui');
Route::get('/testdrop', function () {
    return view('front.testdrop');
});
Route::get('/testsearch', function () {
    return view('front.testsearch');
});
Route::get('/testexport','frontendController@exportexcel');
/*
Route::get('/', function () {
    // Fetch the file info.
    $filePath = public_path('images/bus/3.txt');

    if(file_exists($filePath)) {
        $fileName = basename($filePath);
        $fileSize = filesize($filePath);

        // Output headers.
        header("Cache-Control: private");
        header("Content-Type: application/stream");
        header("Content-Disposition: attachment; filename=".$fileName);

        // Output file.
        readfile ($filePath);
        exit();
    }
    else {
        die('The provided file path is not valid.');
    }
    //return view('welcome');
});*/

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/bus/addrelation.blade.php
@extends('admin.layouts.template')
@section('page_heading')
@section('content')
<div class="container">
    <div class="form-group"><h1 style="font-size:38px;">กระบวนการ </h1></div>
  			<div class="form-group"><h1 style="font-size:38px;">เพิ่มความสัมพันธ์</h1></div>
    <div class="row">
        <div class="col-md-7"></div><div class="form-group"><button id="reset"  class="btn btn-danger">Reset</button></div>
        <form action="addrelation" method = "post" >
         <div class="col-md-8">
             <div class="form-group">ระบบสารสนเทศ</div>
             <div class="dropdown">
            <select  id="app" name="appRelation" class="appr">
                <option value=""></option>
                <?php
                $len = sizeof($aq1);
                ?>
                @if(count($aq1))
                @foreach($apps as $ap)
                    <?php $sta = 0; ?>
                      <?php $re = 0; ?>
                         @foreach($aq1 as $aq)
                             <?php $re++; ?>
                             @if($ap->id != $aq->comp_id)
                                <?php   $sta++; ?>
                                @if($re == $len)
                                    @if($sta == $len)
                                         <option value="{{ $ap->id}}">{{ $ap->name}}</option>
                                    @endif
                                @endif
                           @endif
                        @endforeach
                @endforeach
                @else
                @foreach($apps as $ap)
                <option value="{{ $ap->id}}">{{ $ap->name}}</option>
                @endforeach
                @endif
            </select></div><br>
            <div class="bs-example" data-example-id="bordered-table">
                <div class="panel panel-default" >
                    <div class="panel-heading">
                        เพิ่มความสัมพันธ์ระบบสารสนเทศ
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body" style="margin-right:20px;">
                        <div class="app"></div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            </div>

            <div class="col-md-8">
                <p class="form-group">ข้อมูล</p>
                <div class="dropdown">
            <select  id="data" name="busRelation" class="datar">
                <option value=""></option>
                <?php
                $lend = sizeof($dq1);
                ?>
                @if(count($dq1))
                @foreach($dats as $ds)
                <?php $sta = 0; ?>
                <?php $re = 0; ?>
                @foreach($dq1 as $dq)
                <?php $re++; ?>
                @if($ds->id != $dq->comp_id)
                <?php   $sta++; ?>
                @if($re == $lend)
                @if($sta == $lend)
                <option value="{{ $ds->id}}">{{ $ds->name}}</option>
                @endif
                @endif
                @endif
                @endforeach
                @endforeach
                @else
                @foreach($dats as $ds)
                <option value="{{ $ds->id}}">{{ $ds->name}}</option>
                @endforeach
                @endif


            </select></div><br>
            <div class="bs-example" data-example-id="bordered-table">
                <div class="panel panel-default" >
                    <div class="panel-heading">
                        เพิ่มความสัมพันธ์ข้อมูล
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body" style="margin-right:20px;">
                        <div class="data"></div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            </div>

            <input type="hidden" id="id" name="id" value="{{$app}}" >
            <input type="hidden" id="ar" name="ar" value="" >
            <input type="hidden" id="dr" name="dr" value="" >


            <input type="hidden" id="tpr" name="tpr" value="" >
            <input type="hidden" id="der" name="der" value="" >

            <input type="hidden" name="_token" value="{{csrf_token()}}" >
            <div class="col-md-6">
            <input type="submit" value="ตกลง" id = "add1"  class=" btn btn-success" >
            </div>
            <br>
    </form>

    </div>
</div>

 <br>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        var a=0;
        var i = 0;
        var i1 = 0;
        var i2 = 0;
        var i3 = 0;

        var i5 = 0;
        var i6 = 0;

        var value = new Array();
        var value1 = new Array();
        var valueb = new Array();
        var valueb1 = new Array();
        var valued = new Array();
        var valued1 = new Array();
        var valuet = new Array();
        var valuet1 = new Array();

        var valuetp = new Array();
        var valuetp1 = new Array();
        var valuede = new Array();
        var valuede1 = new Array();

         $('#reset').click(function () {
           // alert("aa")
            location.reload();
            false;
        });
        $('#tp').change(function () {
            var tpq = document.getElementById("tp");
            var selectedTexttp1 = tpq.options[tpq.selectedIndex].text;
            var selectedTexttp = tpq.options[tpq.selectedIndex].value;
            //    var selectedText = $(this).find("option:selected").value();
            valuetp[i5] =  selectedTexttp ;
            valuetp1[i5] =  selectedTexttp1 ;

            $(".tp").text(valuetp1);

            i5++;

        });
        $('#de').change(function () {
            var deq = document.getElementById("de");
            var selectedTextde1 = deq.options[deq.selectedIndex].text;
            var selectedTextde = deq.options[deq.selectedIndex].value;
            //    var selectedText = $(this).find("option:selected").value();
            valuede[i6] =  selectedTextde ;
            valuede1[i6] =  selectedTextde1 ;

            $(".de").text(valuede1);

            i6++;

        });

        $('#app').change(function () {
          var e = document.getElementById("app");
          var selectedText1 = e.options[e.selectedIndex].text;
          var selectedText = e.options[e.selectedIndex].value;
        //    var selectedText = $(this).find("option:selected").value();
            value[i] =  selectedText ;
            value1[i] =  selectedText1 ;

            $(".app").text(value1);

            i++;

        });
        $('#bus').change(function () {
          var b = document.getElementById("bus");
          var selectedTextb1 = b.options[b.selectedIndex].text;
          var selectedTextb = b.options[b.selectedIndex].value;
        //    var selectedText = $(this).find("option:selected").value();
            valueb[i1] =  selectedTextb ;
            valueb1[i1] =  selectedTextb1 ;

            $(".bus").text(valueb1);

            i1++;

        });
        $('#data').change(function () {
          var d = document.getElementById("data");
          var selectedTextd1 = d.options[d.selectedIndex].text;
          var selectedTextd = d.options[d.selectedIndex].value;
        //    var selectedText = $(this).find("option:selected").value();
            valued[i2] =  selectedTextd ;
            valued1[i2] =  selectedTextd1 ;

            $(".data").text(valued1);

            i2++;

        });

        $('#tech').change(function () {
          var t = document.getElementById("tech");
          var selectedTextt1 = t.options[t.selectedIndex].text;
          var selectedTextt = t.options[t.selectedIndex].value;
        //    var selectedText = $(this).find("option:selected").value();
            valuet[i3] =  selectedTextt ;
            valuet1[i3] =  selectedTextt1 ;

            $(".tech").text(valuet1);

            i3++;

        });
        $('#add1').click(function () {
            $('#ar').val(JSON.stringify(value));
          //  $('#br').val(JSON.stringify(valueb));
            $('#dr').val(JSON.stringify(valued));
           // $('#tr').val(JSON.stringify(valuet));

            $('#tpr').val(JSON.stringify(valuetp));
            $('#der').val(JSON.stringify(valuede));

            /*  var text = "";
              var len = value.length;

              for (i = 0; i < len; i++) {
                  text += "<td>" + value[i] + "</td>";
              }
              document.getElementById("content").innerHTML = text;*/
        });


    });
</script>
@stop

resources/views/bus/create.blade.php
@extends('admin.layouts.template')
@section('page_heading','Crate')
@section('content')

<div class="container">
       <div class="row">
           <div class="col-md-7 col-md-offset-1">.

               <div class="panel panel-default">

                   <div class="panel-heading">กระบวนการ</div>

                   <div class="panel-body">

                     {!! Form::open(array('route'=>'bus.store','class' => 'form',
        'novalidate' => 'novalidate',
        'files' => true)) !!}


                                 
                                        <div class="form-group">
                                      {!! Form::label('lv3_id','ระดับกระบวนการ') !!}
                                        {!! Form::select('lv3_id',['' => ''] + $lv, null, ['class' => 'form-control datar']) !!}
                                    </div>

                                    <div class="form-group">
                                        {!! Form::label('name','ชื่อกระบวนการ') !!}
                                        {!! Form::text('name',null,['class'=>'form-control']) !!}
                                    </div>
                                   
                                    <div class="form-group">
                                      {{ Form::label('dic','รูปกระบวนการทำงาน jpg,png,pdf') }}
                                      {{ Form::file('dic',null,['class'=>'form-control']) }}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('file','ไฟล์กระบวนการทำงาน excel,word') !!}
                                        {!! Form::file('file',null,['class'=>'form-control']) !!}
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('remark','รายละเอียด') !!}
                                        {!! Form::textarea('remark',null,['class'=>'form-control']) !!}
                                    </div>
                       {!! Form::label('','ความสัมพันธ์') !!}
                                    <div class="form-group">
                                        {!! Form::label('department_id','หน่วยงานที่เกี่ยวข้อง') !!}
                                    </div>
                                       <div class="form-group">
                                           <select  id="de" name="busRelation" class="datar">
                                               <option value=""></option>
                                               @foreach($items as $is)
                                                   <option value="{{ $is->id}}">{{ $is->name}}</option>
                                               @endforeach
                                           </select>
                                       </div>
                                       <div class="panel panel-default" >
                                           <div class="panel-heading">
                                              หน่วยงาน
                                           </div>
                                           <!-- /.panel-heading -->
                                           <div class="panel-body" style="margin-right:20px;">
                                               <div class="de"><table class="table"></table></div>
                                           </div>
                                           <!-- /.panel-body -->
                                       </div>
                                       <!-- /.panel -->
                       <div class="form-group">
                           {!! Form::label('department_id','ระบบสารสนเทศ') !!}
                       </div>
                       <div class="form-group">
                           <select  id="app" name="busRelation" class="datar">
                               <option value=""></option>
                               @foreach($app456 as $as)
                                   <option value="{{ $as->id}}">{{ $as->name}}</option>
                               @endforeach
                           </select>
                       </div>
                       <div class="panel panel-default" >
                           <div class="panel-heading">
                               ระบบสารสนเทศ
                           </div>
                           <!-- /.panel-heading -->
                           <div class="panel-body" style="margin-right:20px;">
                               <div class="app"><table class="table"></table></div>
                           </div>
                           <!-- /.panel-body -->
                       </div>
                       <!-- /.panel -->
                       <div class="form-group">
                           {!! Form::label('','ข้อมูล') !!}
                       </div>
                       <div class="form-group">
                           <select  id="data" name="busRelation" class="datar">
                               <option value=""></option>
                               @foreach($data456 as $ds)
                                   <option value="{{ $ds->id}}">{{ $ds->name}}</option>
                               @endforeach
                           </select>
                       </div>
                       <div class="panel panel-default" >
                           <div class="panel-heading">
                               ข้อมูล
                           </div>
                           <!-- /.panel-heading -->
                           <div class="panel-body" style="margin-right:20px;">
                               <div class="data"><table class="table"></table></div>
                           </div>
                           <!-- /.panel-body -->
                       </div>
                       <!-- /.panel -->



                         {!! Form::hidden('department', null,['id' => 'department']) !!}
                       {!! Form::hidden('app2', null,['id' => 'app2']) !!}
                       {!! Form::hidden('data2', null,['id' => 'data2']) !!}
                      <div class="form-group">
                          {!! Form::button('เพิ่มกระบวนการ',['type'=>'submit','class'=>'btn btn-primary','id' => 'add1']) !!}
                          {{ link_to_route('bus.index','ย้อนกลับ',null,['class'=>'btn btn-danger']) }}
                                    </div>
                                {!! Form::close() !!}
                   </div>
               </div>
                                     @if($errors->any())
                                    <ul class="alert alert-danger">
                                    @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                    @endif
           </div>
       </div>
   </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        var valuede = new Array();
        var valuede1 = new Array();
        var valueapp = new Array();
        var valueapp1 = new Array();
        var valuedata = new Array();
        var valuedata1 = new Array();
        var i6 = 0;
        var i5 = 0;
        var i4 = 0;
        $('#de').change(function () {
           // alert("aa");
            var aom = 0 ;
            var deq = document.getElementById("de");
            var selectedTextde1 = deq.options[deq.selectedIndex].text;
            var selectedTextde = deq.options[deq.selectedIndex].value;
            for (i = 0; i < valuede.length; i++) {
                if (valuede[i] == selectedTextde ) {
                    var aom = '1';
                }
            }
            if (aom == '1' ){}else {
            valuede[i6] =  selectedTextde ;
            valuede1[i6] =  selectedTextde1 ;
            //$(".de").text(valuede1);

                $('.de table').append("<tr><td>" + valuede1[i6] + "</td><td><button type='button' class='btn btn-danger arraydel' data-id='" + valuede1[i6] + "'" +
                        " data-id1='" + valuede[i6] + "' ><span class='glyphicon glyphicon-remove'></span></button></td></tr><br>");
                i6++;
                $('.de').on('click', '.arraydel', function () {
                   var data = $(this).attr('data-id');
                    var data1 = $(this).attr('data-id1');
                    //alert(data1);
                    valuede1 = jQuery.grep(valuede1, function (value) {
                        return value != data;
                    });
                    valuede = jQuery.grep(valuede, function (value) {
                        return value != data1;
                    });
                    $(this).closest('tr').remove();

                });
            }

        });
        $('#app').change(function () {
            // alert("aa");
            var aom = 0 ;
            var app = document.getElementById("app");
            var selectedTextapp1 = app.options[app.selectedIndex].text;
            var selectedTextapp = app.options[app.selectedIndex].value;
            for (i = 0; i < valueapp.length; i++) {
                if (valueapp[i] == selectedTextapp ) {
                    var aom = '1';
                }
            }
            if (aom == '1' ){}else {
                valueapp[i5] =  selectedTextapp ;
                valueapp1[i5] =  selectedTextapp1 ;
                $('.app table').append("<tr><td>" + valueapp1[i5] + "</td><td><button type='button' class='btn btn-danger arraydel1' data-id='" + valueapp1[i5] + "'" +
                        " data-id1='" + valueapp[i5] + "' ><span class='glyphicon glyphicon-remove'></span></button></td></tr><br>");
                i5++;
                $('.app').on('click', '.arraydel1', function () {
                    var data = $(this).attr('data-id');
                    var data1 = $(this).attr('data-id1');
                    //alert(data1);
                    valueapp1 = jQuery.grep(valueapp1, function (value) {
                        return value != data;
                    });
                    valueapp = jQuery.grep(valueapp, function (value) {
                        return value != data1;
                    });
                    $(this).closest('tr').remove();

                });
            }

        });
        $('#data').change(function () {
            // alert("aa");
            var aom = 0 ;
            var data = document.getElementById("data");
            var selectedTextdata1 = data.options[data.selectedIndex].text;
            var selectedTextdata = data.options[data.selectedIndex].value;
            for (i = 0; i < valuedata.length; i++) {
                if (valuedata[i] == selectedTextdata ) {
                    var aom = '1';
                }
            }
            if (aom == '1' ){}else {
                valuedata[i4] =  selectedTextdata ;
                valuedata1[i4] =  selectedTextdata1 ;
                $('.data table').append("<tr><td>" + valuedata1[i4] + "</td><td><button type='button' class='btn btn-danger arraydel2' data-id='" + valuedata1[i4] + "'" +
                        " data-id1='" + valuedata[i4] + "' ><span class='glyphicon glyphicon-remove'></span></button></td></tr><br>");
                i4++;
                $('.data').on('click', '.arraydel2', function () {
                    var data = $(this).attr('data-id');
                    var data1 = $(this).attr('data-id1');
                    //alert(data1);
                    valuedata1 = jQuery.grep(valuedata1, function (value) {
                        return value != data;
                    });
                    valuedata = jQuery.grep(valuedata, function (value) {
                        return value != data1;
                    });
                    $(this).closest('tr').remove();

                });
            }

        });
        $('#add1').click(function () {
            $('#department').val(JSON.stringify(valuede));
            $('#app2').val(JSON.stringify(valueapp));
            $('#data2').val(JSON.stringify(valuedata));
           //alert(valuedata);
        });


    });
</script>
@stop